Test Restart for ClientEventDealPublished AND ClientEventDealActivated
filecoin-project/go-fil-markets pull request #399
Opened 2020-09-10 08:44 UTC by aarshkshah1992

Closes https://github.com/filecoin-project/lotus/issues/3443.

2020-09-10 16:10 UTC, hannahhoward requested changes
Awesome and generally LGTM.

However, I really prefer to not put time.Sleeps' in test data. what I would rather do is have the DelayFakeCommonNode have channels, and if the boolean is true, it reads from the channel. Then, whenever you want to get it unstuck, you write to the channel. (Can just be a chan struct{})

2020-09-11 06:34 UTC, aarshkshah1992 commented
@hannahhoward Have addressed your review.

2020-09-11 06:46 UTC, aarshkshah1992 commented
@hannahhoward Have addressed your comments.

2020-09-14 18:10 UTC, hannahhoward approved these changes

2020-09-15 04:49 UTC, merged