add protocol to request retrieval ask
filecoin-project/go-fil-markets pull request #632
Opened 2021-09-28 13:06 UTC by dirkmc

2021-10-01 15:05 UTC, nonsense approved these changes

2021-10-05 06:57 UTC, aarshkshah1992 requested changes

2021-10-05 06:57 UTC, aarshkshah1992 commented on retrievalmarket/impl/provider.go
> +func (p *Provider) HandleAskStream(s rmnet.RetrievalAskStream) {
@dirkmc  This wont work. With Dynamic pricing, we quote a different price for each deal based on a number of factors. Just returning the ask from the ask store wont work. Maybe the storage provider has an external script configured for example. You want the client to give you the params it gives you when it actually makes the deal (pieceCid etc.) in the request for this stream and then run it through the same pricing function that we run during retrieval.

2021-10-05 06:57 UTC, aarshkshah1992 commented on retrievalmarket/types.go
> +type SignedRetrievalAsk struct {
@dirkmc  We don't really sign the QueryResponse for the query protocol. So, why are we signing the ask response here ?

2021-10-05 06:57 UTC, aarshkshah1992 commented on retrievalmarket/impl/askstore/askstore_impl.go
> +func (s *AskStoreImpl) GetSignedAsk() (*retrievalmarket.SignedRetrievalAsk, error) {
Why do we need to sign asks ? Also, as commented elsewhere, just returning the ask here without using the pricing function wont be of much use.

2021-11-17 09:15 UTC, dirkmc commented on retrievalmarket/impl/client.go
> +	request := rmnet.AskRequest{Miner: p.Address}
We need to put _some_ parameter in the ask request in order to CBOR marshall it

2021-11-17 09:17 UTC, dirkmc commented on retrievalmarket/impl/client.go
> +	request := rmnet.AskRequest{Miner: p.Address}
I'll change this to the parameters needed for dynamic retrieval pricing

2021-11-17 10:43 UTC, dirkmc commented
Closing as this functionality doesn't add anything new over the `Query` protocol (see `HandleQueryStream`)

2021-11-17 10:43 UTC, closed without merging